version: '3.7'

services:

  web:
    container_name: 'SchoolDockerContainer'
    image: 'aspnetcoreapp'
    build: .
    ports:
     - "80:80"
    depends_on:
     - "db"

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
          - "1433:1433"

    environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"